server:
  port: 8081
spring:
  application:
    name: sharding_jdbc

#sharding-jdbc 的配置
sharding.jdbc:
  datasource:
    name: ds_master,ds_slave_0,ds_slave_1
    ds_master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3316/db
      username: root
      password: root
    ds_slave_0:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3326/db
      username: root
      password: root
    ds_slave_1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3336/db
      username: root
      password: root
    config:
      masterslave:
        name: ds_ms
        master-data-source-name: ds_master
        slave-data-source-name: ds_slave_0,ds_slave_1
        load_balance-algorithm-type: rund_robin
    props:
      sql.show: true
# mybatis的配置
mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations:
    - classpath:mybatis/mappers/*.xml
